/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardList: typeof import('./src/components/CardList/CardList.vue')['default']
    GoodCard: typeof import('./src/components/GoodCard/GoodCard.vue')['default']
    NutAddressList: typeof import('@nutui/nutui-taro')['AddressList']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutBarrage: typeof import('@nutui/nutui-taro')['Barrage']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCard: typeof import('@nutui/nutui-taro')['Card']
    NutCategory: typeof import('@nutui/nutui-taro')['Category']
    NutCategoryPane: typeof import('@nutui/nutui-taro')['CategoryPane']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCollapse: typeof import('@nutui/nutui-taro')['Collapse']
    NutCollapseItem: typeof import('@nutui/nutui-taro')['CollapseItem']
    NutComment: typeof import('@nutui/nutui-taro')['Comment']
    NutCountup: typeof import('@nutui/nutui-taro')['Countup']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutFixedNav: typeof import('@nutui/nutui-taro')['FixedNav']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutNoticebar: typeof import('@nutui/nutui-taro')['Noticebar']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutPrice: typeof import('@nutui/nutui-taro')['Price']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutRate: typeof import('@nutui/nutui-taro')['Rate']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutSku: typeof import('@nutui/nutui-taro')['Sku']
    NutSpace: typeof import('@nutui/nutui-taro')['Space']
    NutStep: typeof import('@nutui/nutui-taro')['Step']
    NutSteps: typeof import('@nutui/nutui-taro')['Steps']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    NutTextarea: typeof import('@nutui/nutui-taro')['Textarea']
    NutUploader: typeof import('@nutui/nutui-taro')['Uploader']
    OrderCard: typeof import('./src/components/OrderDetail/OrderCard.vue')['default']
    OrderList: typeof import('./src/components/OrderList/OrderList.vue')['default']
    OrderManage: typeof import('./src/components/OrderManage/OrderManage.vue')['default']
    ShopList: typeof import('./src/components/ShopList/ShopList.vue')['default']
  }
}
