/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardList: typeof import('./src/components/CardList/CardList.vue')['default']
    NutAddressList: typeof import('@nutui/nutui-taro')['AddressList']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutBarrage: typeof import('@nutui/nutui-taro')['Barrage']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCard: typeof import('@nutui/nutui-taro')['Card']
    NutCategory: typeof import('@nutui/nutui-taro')['Category']
    NutCategoryPane: typeof import('@nutui/nutui-taro')['CategoryPane']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutComment: typeof import('@nutui/nutui-taro')['Comment']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutFixedNav: typeof import('@nutui/nutui-taro')['FixedNav']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutNoticebar: typeof import('@nutui/nutui-taro')['Noticebar']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutSku: typeof import('@nutui/nutui-taro')['Sku']
    NutStep: typeof import('@nutui/nutui-taro')['Step']
    NutSteps: typeof import('@nutui/nutui-taro')['Steps']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    ShopList: typeof import('./src/components/ShopList/ShopList.vue')['default']
  }
}
